org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

author=SrNadien
modid=CompactMachinerooms
mod_named=CompactMachineRoomsEnabler


mcversion=1.21.1
neoversion=21.1.215
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

#jei
jei_version_id=7270455

#compact machines
compact_machines_version_id=7362352

mod_version=1.0.0
# tag_version=Revived
tag_lanzador= NeoForge
